Update android.yml

diff --git a/.github/workflows/android.yml b/.github/workflows/android.yml
--- a/.github/workflows/android.yml
+++ b/.github/workflows/android.yml
@@ -83,8 +83,16 @@ jobs:
       - name: ccache
         uses: hendrikmuhs/ccache-action@main
         with:
-          key: ${{ matrix.arch }}
-          max-size: 2G
+          key: angle-ccache
+          max-size: 5G
+
+      - name: Setup ccache path
+        shell: bash
+        run: |
+         echo "$HOME/.local/bin" >> $GITHUB_PATH
+         echo "/usr/lib/ccache" >> $GITHUB_PATH
+         which ccache || echo "ccache not found"
+         ccache --version
 
       - name: Build ANGLE
         shell: bash
